package com.ispeakconfidence.app;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.graphics.*;import android.hardware.display.*;import android.media.Image;import android.media.ImageReader;import android.media.projection.*;import android.net.Uri;import android.os.*;import android.util.DisplayMetrics;import android.view.WindowManager;import java.io.*;import java.net.*;import java.nio.ByteBuffer;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;

public class ScreenShareService extends Service{
 public static final String ACTION_START="com.ispeakconfidence.app.START_SCREEN_SHARE",ACTION_STOP="com.ispeakconfidence.app.STOP_SCREEN_SHARE"; private MediaProjection projection;private VirtualDisplay display;private ImageReader reader;private HandlerThread thread;private ExecutorService uploader;private final AtomicBoolean uploading=new AtomicBoolean(false);private long lastFrame=0;private String booking="",token="";private boolean stopping=false;
 @Override public void onCreate(){super.onCreate();uploader=Executors.newSingleThreadExecutor();if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("ispeak_screen","iSpeak screen sharing",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private Notification note(){return new Notification.Builder(this,Build.VERSION.SDK_INT>=26?"ispeak_screen":null).setContentTitle("iSpeak screen sharing").setContentText("Your screen is being shared in the classroom").setSmallIcon(android.R.drawable.presence_video_online).setOngoing(true).build();}
 @Override public int onStartCommand(Intent i,int flags,int id){if(i==null)return START_NOT_STICKY;if(ACTION_STOP.equals(i.getAction())){stopShare(true);return START_NOT_STICKY;}if(Build.VERSION.SDK_INT>=29)startForeground(1868,note(),ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);else startForeground(1868,note());booking=i.getStringExtra("bookingId");token=i.getStringExtra("authToken");Intent data=Build.VERSION.SDK_INT>=33?i.getParcelableExtra("projectionData",Intent.class):(Intent)i.getParcelableExtra("projectionData");int rc=i.getIntExtra("resultCode",Activity.RESULT_CANCELED);if(data==null||booking==null||token==null){stopShare(false);return START_NOT_STICKY;}MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(rc,data);if(projection==null){stopShare(false);return START_NOT_STICKY;}projection.registerCallback(new MediaProjection.Callback(){@Override public void onStop(){stopShare(true);}},new Handler(Looper.getMainLooper()));startCapture();return START_NOT_STICKY;}
 private void startCapture(){DisplayMetrics dm=new DisplayMetrics();((WindowManager)getSystemService(WINDOW_SERVICE)).getDefaultDisplay().getRealMetrics(dm);int sw=dm.widthPixels,sh=dm.heightPixels,w=Math.min(720,sw),h=Math.max(2,(int)Math.round(sh*(w/(double)sw)));if((h&1)==1)h--;thread=new HandlerThread("iSpeakScreenCapture");thread.start();reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);display=projection.createVirtualDisplay("iSpeakClassroomScreen",w,h,dm.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,new Handler(thread.getLooper()));reader.setOnImageAvailableListener(r->{Image img=null;try{img=r.acquireLatestImage();long now=System.currentTimeMillis();if(img==null||now-lastFrame<700||uploading.get())return;lastFrame=now;Image.Plane p=img.getPlanes()[0];ByteBuffer b=p.getBuffer();int ps=p.getPixelStride(),rs=p.getRowStride(),pad=rs-ps*w;Bitmap wide=Bitmap.createBitmap(w+pad/ps,h,Bitmap.Config.ARGB_8888);wide.copyPixelsFromBuffer(b);Bitmap crop=Bitmap.createBitmap(wide,0,0,w,h);ByteArrayOutputStream out=new ByteArrayOutputStream();crop.compress(Bitmap.CompressFormat.JPEG,45,out);wide.recycle();crop.recycle();byte[] bytes=out.toByteArray();uploading.set(true);uploader.execute(()->{try{upload(bytes,"frame");}finally{uploading.set(false);}});}catch(Exception ignored){}finally{if(img!=null)img.close();}},new Handler(thread.getLooper()));}
 private void upload(byte[] body,String action){HttpURLConnection c=null;try{URL u=new URL("https://ispeakconfidence.com/api/classroom-screen-frame/"+Uri.encode(booking));c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(7000);c.setReadTimeout(7000);c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("X-iSpeak-Client","web-app");c.setRequestProperty("X-Screen-Share-Action",action);c.setRequestProperty("Content-Type","image/jpeg");if(body!=null)c.getOutputStream().write(body);try{InputStream in=c.getInputStream();while(in.read()!=-1){}in.close();}catch(Exception ignored){}}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}}
 private void stopShare(boolean notify){if(stopping)return;stopping=true;if(notify&&booking!=null&&!booking.isEmpty()&&token!=null&&!token.isEmpty()&&uploader!=null)uploader.execute(()->upload(new byte[0],"stop"));try{if(reader!=null)reader.close();}catch(Exception ignored){}try{if(display!=null)display.release();}catch(Exception ignored){}try{if(projection!=null)projection.stop();}catch(Exception ignored){}reader=null;display=null;projection=null;if(thread!=null){thread.quitSafely();thread=null;}stopForeground(true);stopSelf();}
 @Override public void onDestroy(){stopShare(false);if(uploader!=null)uploader.shutdownNow();super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
