const fs=require('fs');const path=require('path');
const root=__dirname;let pass=0,fail=0;function check(name,ok){if(ok){console.log('PASS',name);pass++}else{console.error('FAIL',name);fail++}}
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),server=fs.readFileSync(path.join(root,'server.js'),'utf8'),support=fs.readFileSync(path.join(root,'language-support-v17-5.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
check('V18 schema',/schemaVersion:1800/.test(app));check('learner model default',/learnerModel:\{\}/.test(app));check('learner evidence helper',/function recordLearningEvidence/.test(app));check('confidence helper',/function learningConfidence/.test(app));check('local yesterday helper used',/localDateOffset\(-1\)/.test(app));check('no quick UTC yesterday bug',!app.includes('new Date(Date.now()-86400000).toISOString().slice(0,10)'));check('cloud sync learner model',server.includes("'learnerModel'"));check('cloud sync error history',server.includes("'errorHistory'"));check('cloud sync skill evidence',server.includes("'skillEvidence'"));check('translation coverage function',/function coverage\(/.test(support));check('translation fallback remains visible',app.includes('support-fallback'));check('Khmer remains guarded',support.includes("uiLang!=='khmer'"));
check('server V18.5.0',server.includes("version:'V18.5.0'"));check('placement V18.5.0',app.includes("version:'18.5.0'"));check('service worker V18.5.0',sw.includes('ispeak-v18-5-0'));check('V18.5.0 BAT exists',fs.existsSync(path.join(root,'start-v18-5-0.bat')));check('legacy start BAT removed',fs.readdirSync(root).filter(x=>/^start-v/.test(x)&&x!=='start-v18-5-0.bat').length===0);check('learner insights UI',app.includes('Learning intelligence'));check('no AI key embedded',!app.includes('GEMINI_API_KEY=')&&!server.includes('AIza'));check('no SMTP secret embedded',!server.includes('SMTP_APP_PASSWORD='));
check('classroom authenticated route',server.includes('classroomMatch')&&server.includes('classroomAccess'));check('classroom WebRTC client',app.includes('RTCPeerConnection')&&app.includes('openISpeakClassroom'));check('classroom recording consent gate',server.includes('recordingReady(access.room)'));check('recording content validation',server.includes('fileMagicOk(buf,mimeType)'));check('admin replay protected',server.includes("access.role!=='admin'"));check('verified lesson reviews',server.includes("action==='review'")&&server.includes('teacherReviewSummary'));check('monitoring notice in terms',fs.readFileSync(path.join(root,'terms.html'),'utf8').includes('monitoring and recordings'));check('admin PIN not accepted in URL query',!server.includes("searchParams.get('adminPin')"));check('upload extension derived from MIME',server.includes('extByMime'));check('PNG structural validation',server.includes("subarray(12,16).toString()==='IHDR'"));check('MP4 structural validation',server.includes("scan.includes('moov')||scan.includes('mdat')"));check('CSP header enabled',server.includes("Content-Security-Policy"));check('sensitive static paths blocked',server.includes("rel.startsWith('data/')")&&server.includes('server\\.js'));const ids=[...html.matchAll(/\bid=["']([^"']+)/g)].map(x=>x[1]);check('no duplicate HTML IDs',new Set(ids).size===ids.length);
const core=(sw.match(/CORE=\[(.*?)\];/)||[])[1]||'';const items=[...core.matchAll(/'([^']+)'/g)].map(x=>x[1]);check('all PWA core files exist',items.every(x=>x==='/'||fs.existsSync(path.join(root,x.replace(/^\//,'')))));

// V18.4 deep-release audit additions.
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')),lock=JSON.parse(fs.readFileSync(path.join(root,'package-lock.json'),'utf8'));
check('package metadata synchronized',pkg.version==='18.5.0'&&lock.version==='18.5.0'&&lock.packages?.['']?.version==='18.5.0');
check('visible page title current',html.includes('<title>iSpeak Confidence V18.5.0</title>')&&!html.includes('V18.0.2'));
check('runtime has no stale V18.0.2 marker',![app,server,sw,html].some(x=>x.includes('V18.0.2')));
check('manual offline cache current',app.includes("caches.open('ispeak-v18-5-0-core')"));
for(const dep of ['/curriculum-data.js','/curriculum-expansion-v17-4.js','/ielts-data.js','/khmer-commonvoice-data.js','/language-support-v17-5.js'])check(`offline core includes ${dep}`,core.includes(`'${dep}'`));
check('shared teacher PIN UI removed',!app.includes('legacyTeacherAccess')&&!app.includes('legacyTeacherPortalLogin'));
check('shared teacher PIN API removed',!server.includes("pathname==='/api/teacher/portal'")&&!server.includes('validPortalPin'));
check('shared teacher PIN config removed',!fs.readFileSync(path.join(root,'.env.example'),'utf8').includes('TEACHER_PORTAL_PIN'));
check('Arabic common-question punctuation corrected',support.includes("arabic:'من أين أنت؟'")&&!support.includes("arabic:'من أين أنت？'"));
check('library search has accessible name',/id="librarySearch"[^>]*aria-label=/.test(html));
check('library sort has accessible name',/id="librarySort"[^>]*aria-label=/.test(html));
check('buddy chat input has accessible name',/id="chatText"[^>]*aria-label=/.test(html));
// Local runtime references.
const runtimeFiles=['index.html','styles.css','app.js','manifest.webmanifest','sw.js','language-support-v17-5.js','curriculum-data.js','curriculum-expansion-v17-4.js','ielts-data.js','khmer-commonvoice-data.js'];
let missingRefs=[];for(const fn of runtimeFiles){const t=fs.readFileSync(path.join(root,fn),'utf8');for(const m of t.matchAll(/["'`](\/?(?:assets|library-books)\/[^"'`$?#\s<>]+)["'`]/g)){const rel=m[1].replace(/^\//,'');if(!fs.existsSync(path.join(root,rel)))missingRefs.push(`${fn}: ${rel}`)}}check('all local runtime asset/book references exist',missingRefs.length===0);
// Curriculum integrity: all languages retain 30 distinct units and do not repeat exact anchor targets.
const vm=require('vm'),ctx={window:{}};vm.createContext(ctx);for(const f of ['curriculum-data.js','curriculum-expansion-v17-4.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});let curriculumOK=true;for(const [lang,obj] of Object.entries(ctx.window.ISC_CURRICULUM.languages||{})){const units=obj.units||[];if(units.length!==30||new Set(units.map(u=>u.title)).size!==30)curriculumOK=false;const a=[];for(const u of units)for(const x of u.anchors||[])a.push(String(x.target||'').normalize('NFC').trim().toLowerCase());if(a.filter(Boolean).length!==new Set(a.filter(Boolean)).size)curriculumOK=false;}check('30-unit curriculum integrity and no exact anchor repetition',curriculumOK);
// Library integrity: no empty chapters/pages, no exact duplicate pages, and metadata chapter counts agree with files.
let libraryOK=true;const pageHashes=new Set();for(const f of fs.readdirSync(path.join(root,'library-books','processed')).filter(x=>x.endsWith('.json'))){const d=JSON.parse(fs.readFileSync(path.join(root,'library-books','processed',f),'utf8'));if(!Array.isArray(d.chapters)||!d.chapters.length){libraryOK=false;continue}const local=new Set();for(const ch of d.chapters){if(!String(ch.title||'').trim()||!Array.isArray(ch.pages)||!ch.pages.length)libraryOK=false;for(const pg of ch.pages){const norm=String(pg||'').replace(/\s+/g,' ').trim();if(!norm)libraryOK=false;const h=require('crypto').createHash('sha256').update(norm).digest('hex');if(local.has(h))libraryOK=false;local.add(h);if(norm.length<80&&ch.pages.length>1)libraryOK=false;}}}check('processed library has no empty/duplicate/broken fragment pages',libraryOK);
let metaOK=true;for(const m of app.matchAll(/\{id:"([^"]+)"[\s\S]*?dataFile:"([^"]+)"[\s\S]*?chapterCount:(\d+)/g)){const fp=path.join(root,m[2]);if(!fs.existsSync(fp)||JSON.parse(fs.readFileSync(fp,'utf8')).chapters.length!==Number(m[3]))metaOK=false;}check('library metadata chapter counts match files',metaOK);

check('admin portal hidden from learner teacher page',!html.includes('id="applicationAdminBtn"')&&!html.includes('>Admin Portal</button>'));
check('student schedule and classroom navigation visible',html.includes('id="studentScheduleBtn"')&&html.includes('id="studentClassroomBtn"')&&app.includes('function openStudentSchedule')&&app.includes('function openStudentClassroomCentre'));
check('/admin route opens admin login',app.includes("location.pathname.replace(/\\/+$/,'')==='/admin'")&&app.includes('setTimeout(applicationAdminLogin,80)'));
check('admin dashboard available',app.includes('function openAdminDashboard')&&app.includes('Teachers & Applications')&&app.includes('Classroom Monitoring'));
check('existing Nathan account provisioning exposed',app.includes("['Nathan','Ounnoun','Jessica','An Sievly']")&&app.includes("action:'createExistingTeacherAccount'"));

check('comprehensive localization layer present',app.includes('const APP_UI_TEXT=')&&app.includes('const APP_UI_TEXT_EXTRA=')&&app.includes('function localizeDocument'));
check('localization observes dynamic UI',app.includes('new MutationObserver')&&app.includes('characterData:true'));
check('course names localize to interface language',app.includes('localizedCourseName(k)')&&app.includes("appTr('sessions')")&&app.includes("appTr('study days')"));
check('header language names localize',app.includes('localizedCourseName(current)')&&app.includes('localizedCourseName(k)'));
check('Spanish buddy banner localized',app.includes("'GAME-STYLE CONVERSATION':'CONVERSACIÓN TIPO JUEGO'"));
check('all six non-English interface packs have teacher portal translation',['Portal del profesor','Portail professeur','教师门户','講師ポータル','بوابة المعلم','វិបផតថលគ្រូ'].every(x=>app.includes(x)));
check('all six non-English interface packs have booking translation',['Reservar una clase','Réserver un cours','预约课程','レッスンを予約','احجز درساً','កក់មេរៀន'].every(x=>app.includes(x)));
check('all six non-English interface packs have IELTS translation',['Preparación IELTS','Préparation IELTS','IELTS 备考','IELTS対策','التحضير لـ IELTS','ការត្រៀម IELTS'].every(x=>app.includes(x)));
console.log(`\nV18.5.0 QA: ${pass} passed, ${fail} failed`);process.exit(fail?1:0);
