const fs=require('fs');
const app=fs.readFileSync('app.js','utf8'),server=fs.readFileSync('server.js','utf8'),css=fs.readFileSync('styles.css','utf8'),pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const checks=[];const test=(name,ok)=>{checks.push([name,!!ok]);console.log(`${ok?'PASS':'FAIL'} ${name}`)};
test('V18.7.1 server status',server.includes("version:'V18.7.1'"));
test('PostgreSQL dependency declared',pkg.dependencies?.pg);
test('PostgreSQL state table initialization',server.includes('CREATE TABLE IF NOT EXISTS ispeak_state'));
test('PostgreSQL imports existing state',server.includes("SELECT data FROM ispeak_state WHERE key=$1")&&server.includes("INSERT INTO ispeak_state"));
test('Local atomic JSON fallback retained',server.includes('atomicJsonSave')&&server.includes("file+'.bak'"));
test('Nathan server price is $0.50',server.includes('NATHAN_BETA_PRICE=0.50')&&server.includes('teacherListedRate(teacher,t)'));
test('Other tutor standard price retained',server.includes('STUDENT_LESSON_PRICE=13'));
test('Booking quote uses server-side teacher rate',server.includes('base=teacherListedRate(teacher,t)'));
test('Admin analytics API exists',server.includes("pathname==='/api/admin/analytics'"));
test('Admin analytics dashboard exists',app.includes('openAdminAnalytics')&&app.includes('User & Product Analytics'));
test('Analytics does not store raw email',server.includes('userHash:')&&!server.includes('user:String(details.user'));
test('Analytics tracks core funnel',server.includes('teacherViews')&&server.includes('bookingStarts')&&server.includes('libraryOpens')&&server.includes('ieltsOpens'));
test('Mobile tutor photos avoid zoom crop',css.includes('@media(max-width:900px)')&&css.includes('object-fit:contain!important'));
test('Story progress tracking retained',app.includes("trackAnalytics('story_open'")&&app.includes('heroReadingProgress'));
test('IELTS cloud progress retained',app.includes('ieltsProgress')&&server.includes("'ieltsProgress'"));
test('No inline onclick handlers added to story series',!/<[^>]+onclick=/i.test(app.match(/function heroesHome[\s\S]{0,15000}/)?.[0]||''));
test('Nathan Revolut URL server-controlled',server.includes("NATHAN_BETA_REVOLUT_URL='https://checkout.revolut.com/pay/046658de-c86d-4b17-b654-ca60fdc910eb'")&&server.includes('checkoutUrl:revolutBeta?NATHAN_BETA_REVOLUT_URL:null'));
test('Revolut only allowed for Nathan beta $0.50',server.includes("body.paymentMode==='revolut_external'&&quote.isNathanBeta&&quote.studentTotal===NATHAN_BETA_PRICE"));
test('External payment not auto-marked paid',server.includes("paymentStatus:revolutBeta?'pending_verification':'paid'")&&server.includes("status:revolutBeta?'payment_pending':'confirmed'"));
test('Nathan beta promo mismatch prevented',server.includes("Promo codes are disabled during Nathan\\'s $0.50 beta payment test."));
test('Frontend opens Revolut checkout returned by server',app.includes("result.checkoutUrl")&&app.includes("paymentMode:'revolut_external'"));
const failed=checks.filter(x=>!x[1]);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed`);if(failed.length)process.exit(1);
