const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
let checks=[];function ok(name,pass){if(!pass)throw new Error('FAIL: '+name);checks.push('PASS: '+name)}
const app=read('app.js'),html=read('index.html'),sw=read('sw.js'),server=read('server.js'),cur=read('curriculum-data.js');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(cur,sandbox);const C=sandbox.window.ISC_CURRICULUM;
ok('V17.3 title',html.includes('V17.3.0'));
ok('V17.3 state schema',app.includes("isc-v17-3-0")&&app.includes('schemaVersion=1730'));
ok('V17.2 migration retained',app.includes("isc-v17-2-1"));
ok('curriculum version',C.version==='17.3.0-learning-engine-rebuild');
ok('30 units in every language',Object.values(C.languages).every(x=>x.units.length===30));
ok('English depth expanded',C.languages.english.units.reduce((n,u)=>n+u.anchors.length,0)>=160);
ok('Khmer learner content preserved',C.languages.khmer.units.reduce((n,u)=>n+u.anchors.length,0)===60);
ok('Can-do outcomes on all units',Object.values(C.languages).every(x=>x.units.every(u=>typeof u.canDo==='string'&&u.canDo.length>20)));
ok('Transfer challenges on all units',Object.values(C.languages).every(x=>x.units.every(u=>typeof u.transfer==='string'&&u.transfer.length>20)));
ok('Language-specific grammar maps', ['english','spanish','french','mandarin','japanese','arabic'].every(l=>C.languages[l].units.every(u=>u.grammarFocus&&u.grammarFocus.length>20)));
ok('Culture/usage notes', ['english','spanish','french','mandarin','japanese','arabic'].every(l=>C.languages[l].units.every(u=>u.cultureNote)));
ok('Skill evidence graph',html.includes('id="skillGraph"')&&app.includes('skillEvidence'));
ok('Error history evidence',app.includes('errorHistory'));
ok('Interactive story has 4 stages',app.includes('4/4 • Transfer')&&app.includes('2/4 • Decide'));
ok('Production game exists',app.includes('data-game-mode="produce"'));
ok('Dictation game exists',app.includes('data-game-mode="dictation"'));
ok('Reconstruction game exists',app.includes('data-game-mode="reconstruct"'));
ok('Error detective game exists',app.includes('data-game-mode="error"'));
ok('Grammar renderer uses grammarFocus',app.includes('u.grammarFocus'));
ok('Transfer renderer uses unit transfer',app.includes('u.transfer'));
ok('No scheduled spaced repetition language remains',!cur.toLowerCase().includes('spaced review'));
ok('Current service worker cache',sw.includes('ispeak-v17-3-0-core'));
ok('Server reports V17.3',server.includes("version:'V17.3.0'"));
console.log(checks.join('\n'));console.log(`\n${checks.length} V17.3.0 learning-engine checks passed.`);
