const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');let pass=0,fail=0;
function ok(c,m){if(c){console.log('PASS',m);pass++}else{console.error('FAIL',m);fail++}}
const ctx={window:{},console};vm.createContext(ctx);for(const f of ['curriculum-data.js','curriculum-expansion-v17-4.js','language-support-v17-5.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const C=ctx.window.ISC_CURRICULUM,S=ctx.window.ISC_SUPPORT,langs=S.order;
ok(!!C&&!!S,'curriculum + support layer load');ok(langs.length===7,'7 app/support languages present');
let dirs=0,nonempty=0,targets=0;for(const base of langs)for(const target of langs){if(base===target)continue;dirs++;const a=C.languages[target].units[0].anchors[0];const r=S.translateMeaning(a.meaning,base,target);if(String(r.text||'').trim())nonempty++;if(String(a.target||'').trim())targets++;}
ok(dirs===42,'all 42 base→target language directions exist');ok(nonempty===42,'all 42 directions render support text without crashing');ok(targets===42,'target-language text remains present in all 42 directions');
let english=true;for(const target of langs)for(const u of C.languages[target].units)for(const a of u.anchors)if(!S.translateMeaning(a.meaning,'english',target).text)english=false;ok(english,'English support covers every current anchor');
ok(/^مرح/.test(S.translateMeaning('Hello','arabic','english').text),'Arabic support renders Arabic for known lesson meaning');ok(S.translateMeaning('Hello','mandarin','english').text==='你好','Mandarin support renders Chinese');ok(S.translateMeaning('Hello','spanish','english').text==='Hola','Spanish support renders Spanish');ok(S.translateMeaning('Hello','french','english').text==='Bonjour','French support renders French');ok(S.translateMeaning('Hello','japanese','english').text==='こんにちは','Japanese support renders Japanese');
const kh=S.translateMeaning('Unapproved test sentence','khmer','english');ok(kh.fallback===true,'unapproved Khmer support is not fabricated');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
ok(app.includes("localStorage.setItem('isc-v17-5-0'"),'V17.5 state key + migration');ok(app.includes('supportMeaningMarkup'),'dual-language meaning renderer wired into app');ok(app.includes('directionMarkup()'),'support→learning language direction UI wired');ok(app.includes("lessonT('fromSupport')"),'speaking no longer assumes English explanation language');ok(app.includes('${supportLangName()} meaning'),'placement no longer hardcodes English meaning');ok(html.includes('language-support-v17-5.js'),'language support loads before app');ok(html.includes('data-direction-summary'),'direction summary is visible on home/learn');ok(sw.includes('language-support-v17-5.js'),'support layer cached offline');ok(sw.includes('curriculum-expansion-v17-4.js'),'expanded curriculum cached offline');
console.log(`\nV17.5 QA: ${pass} passed, ${fail} failed`);process.exit(fail?1:0);
