const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const app=read('app.js'),server=read('server.js'),html=read('index.html'),sw=read('sw.js');
const checks=[];const ok=(name,cond)=>{assert.ok(cond,name);checks.push('PASS '+name)};
ok('local calendar-date helper avoids UTC streak bug',app.includes('d.getFullYear()')&&!app.startsWith("const today=()=>new Date().toISOString"));
ok('V17.2 state key + migration fallback',app.includes("isc-v17-2-0")&&app.includes("isc-v16-0-6"));
ok('Library notes included in cloud whitelist',server.includes("'libraryNotes'"));
ok('Placement metadata is V17.2',app.includes("version:'17.2.0'"));
ok('Advanced conversation uses selected-language mascot',app.includes('mascotProfiles[languages[state.language].mascot].name'));
ok('Booking uses IANA timezone conversion',app.includes('zonedLocalToUtc')&&server.includes('validTimeZone'));
ok('Booking horizon expanded to 60 days',server.includes('availableDays(teacher,60)'));
ok('Approved tutors hydrate into marketplace',app.includes('hydrateApprovedTeachers')&&server.includes("/api/approved-teachers"));
ok('Qualification files require authorization',server.includes("name.includes('-certificate-')")&&server.includes('Private qualification file'));
ok('Upload signatures validated server-side',server.includes('fileMagicOk'));
ok('Signed-in students can fetch live booking status',server.includes("/api/my-bookings")&&app.includes("/api/my-bookings"));
ok('Admin applications entry hidden from normal learner UI',html.includes('applicationAdminBtn')&&html.includes('hidden'));
ok('Keyboard focus styling present',read('styles.css').includes(':focus-visible'));
ok('Reduced-motion accessibility present',read('styles.css').includes('prefers-reduced-motion'));
ok('Offline cache bumped',sw.includes('ispeak-v17-2-0-core')&&app.includes('ispeak-v17-2-0-core'));
ok('AI configuration untouched',server.includes('GEMINI_API_KEY'));
ok('Email configuration untouched',server.includes('SMTP_USER'));
console.log(checks.join('\n'));console.log(`\n${checks.length} V17.2 regression checks passed.`);
