const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const app=read('app.js'),server=read('server.js'),html=read('index.html'),sw=read('sw.js'),curr=read('curriculum-data.js');
const checks=[];const ok=(name,cond)=>{assert.ok(cond,name);checks.push('PASS '+name)};
ok('V17.2.1 state schema + backward migration',app.includes("isc-v17-2-1")&&app.includes("isc-v17-2-0")&&app.includes('schemaVersion:1721'));
ok('local date helper avoids UTC streak bug',app.includes('d.getFullYear()')&&!app.startsWith("const today=()=>new Date().toISOString"));
ok('Library notes normalized and cloud-synced',app.includes("'writingMastery','libraryNotes'")&&server.includes("'libraryNotes'"));
ok('placement metadata updated',app.includes("version:'17.2.1'"));
ok('selected-language mascot used for advanced conversation',app.includes('mascotProfiles[languages[state.language].mascot].name'));
ok('no spaced-review wording remains in curriculum',!curr.toLowerCase().includes('spaced review'));
ok('free-text course completion requires meaningful production',app.includes('meaningfulProduction')&&app.includes('!meaningfulProduction(v,18)'));
ok('IELTS mastery UI matches 8 scored questions',app.includes("'8-question mixed checkpoint'")&&app.includes('qs.slice(0,8)'));
ok('IELTS vocabulary requires written production',app.includes('Complete every vocabulary production challenge'));
ok('IELTS grammar requires written production',app.includes('Complete every grammar drill'));
ok('IELTS writing rejects filler-only word-count completion',app.includes('meaningfulIELTSWriting')&&app.includes('Repeated words or filler text'));
ok('certificate email requires authenticated server verification',server.includes('Sign in first so iSpeak can verify course completion')&&server.includes('Server progress shows')&&server.includes('serverVerified:true'));
ok('client certificate email sends authenticated API request',app.includes("apiJSON('/api/certificate/email'"));
ok('booking uses IANA timezone conversion',app.includes('zonedLocalToUtc')&&server.includes('validTimeZone'));
ok('booking horizon remains 60 days',server.includes('availableDays(teacher,60)'));
ok('approved tutors hydrate into marketplace',app.includes('hydrateApprovedTeachers')&&server.includes('/api/approved-teachers'));
ok('qualification documents protected through API',server.includes("name.includes('-certificate-')")&&server.includes('Private qualification file'));
ok('static server blocks data directory',server.includes("rel.startsWith('data/')"));
ok('static server blocks dotfiles such as .env',server.includes("x.startsWith('.')"));
ok('static path traversal uses path.relative containment',server.includes('path.relative(root,file)'));
ok('malformed URL decoding cannot crash server',server.includes("catch{return send(res,400,'Bad request'"));
ok('basic security response headers enabled',server.includes('X-Content-Type-Options')&&server.includes('Referrer-Policy'));
ok('initial service-worker cache no longer preloads IELTS/books',sw.includes('ispeak-v17-2-1-core')&&!sw.includes("'/ielts-data.js'")&&!sw.includes('/library-books/processed/'));
ok('application admin entry hidden from normal learner UI',html.includes('applicationAdminBtn')&&html.includes('hidden'));
ok('keyboard/reduced-motion accessibility retained',read('styles.css').includes(':focus-visible')&&read('styles.css').includes('prefers-reduced-motion'));
ok('AI and email configuration left intact',server.includes('GEMINI_API_KEY')&&server.includes('SMTP_USER'));
console.log(checks.join('\n'));console.log(`\n${checks.length} V17.2.1 regression checks passed.`);
